In function 'test':
tests/cpychecker/refcounts/uninitialized_data/comparison/input.c:41:nn: warning: comparison against uninitialized data (item) at tests/cpychecker/refcounts/uninitialized_data/comparison/input.c:41 [enabled by default]
tests/cpychecker/refcounts/uninitialized_data/comparison/input.c:34:nn: note: when PyList_New() succeeds at:     result = PyList_New(len);
tests/cpychecker/refcounts/uninitialized_data/comparison/input.c:35:nn: note: taking False path at:     if (!result) {
tests/cpychecker/refcounts/uninitialized_data/comparison/input.c:39:nn: note: reaching:     for (i = 0; i < len; i++) {
tests/cpychecker/refcounts/uninitialized_data/comparison/input.c:39:nn: note: when considering range: 1 <= len <= 0x7fffffff at:     for (i = 0; i < len; i++) {
tests/cpychecker/refcounts/uninitialized_data/comparison/input.c:39:nn: note: taking True path at:     for (i = 0; i < len; i++) {
tests/cpychecker/refcounts/uninitialized_data/comparison/input.c:41:nn: note: reaching: 	if (!item) {
tests/cpychecker/refcounts/uninitialized_data/comparison/input.c:29:nn: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/uninitialized_data/comparison/input.c.test-refcount-errors.html'
