Trace 0:
  Transitions:
    'PyGILState_Ensure'
    'calling PyGILState_Release()'
    'returning'
  Exception:
    (struct PyObject *)0 from tests/cpychecker/refcounts/PyGILState_Ensure/correct/input.c:28
