In function 'test':
tests/cpychecker/refcounts/attributes/returns-borrowed-ref/incorrect-marking/input.c:45:nn: warning: memory leak: ob_refcnt of return value is 1 too high [enabled by default]
tests/cpychecker/refcounts/attributes/returns-borrowed-ref/incorrect-marking/input.c:45:nn: note: return value was allocated at:     return PyLong_FromLong(42);
tests/cpychecker/refcounts/attributes/returns-borrowed-ref/incorrect-marking/input.c:45:nn: note: was expecting final owned ob_refcnt of return value to be 0 since nothing references it but final ob_refcnt is refs: 1 owned
tests/cpychecker/refcounts/attributes/returns-borrowed-ref/incorrect-marking/input.c:45:nn: note: when PyLong_FromLong() succeeds at:     return PyLong_FromLong(42);
tests/cpychecker/refcounts/attributes/returns-borrowed-ref/incorrect-marking/input.c:45:nn: note: ob_refcnt is now refs: 1 owned
tests/cpychecker/refcounts/attributes/returns-borrowed-ref/incorrect-marking/input.c:45:nn: note: returning at:     return PyLong_FromLong(42);
tests/cpychecker/refcounts/attributes/returns-borrowed-ref/incorrect-marking/input.c:40:nn: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/attributes/returns-borrowed-ref/incorrect-marking/input.c.test-refcount-errors.html'
